"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_redux_1 = require("react-redux");
require("./css/AboutMe.css");
var AboutMe = function () { return (React.createElement("div", { className: 'about-me' },
    React.createElement("div", { className: 'about-me-text-container' },
        React.createElement("div", { className: 'about-me-title' },
            React.createElement("p", null, "About Me"),
            React.createElement("hr", null)),
        React.createElement("div", null,
            React.createElement("p", null,
                "Hi, I\u2019m Vinny. I\u2019m a Software Engineer with professional experience in ",
                React.createElement("mark", null, "aerospace"),
                ", ",
                React.createElement("mark", null, "social"),
                ", and ",
                React.createElement("mark", null, "financial "),
                "companies large and small."),
            React.createElement("p", null, "I take pride in solving puzzles like turning business rules into code, orchestrating processes, and designing UI\u2019s."),
            React.createElement("p", null, "As a software engineer, it is my job to find the best tools to solve the problems at hand. Throughout my career, I\u2019ve worked professionally across many technologies to accomplish this. Here\u2019s a list of my favorites:"),
            React.createElement("div", { className: 'tech-list-container' },
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("p", null, "C#")),
                    React.createElement("li", null,
                        React.createElement("p", null, "Java")),
                    React.createElement("li", null,
                        React.createElement("p", null, "Python")),
                    React.createElement("li", null,
                        React.createElement("p", null, "C++"))),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("p", null, "C")),
                    React.createElement("li", null,
                        React.createElement("p", null, "SQL")),
                    React.createElement("li", null,
                        React.createElement("p", null, "NoSQL")),
                    React.createElement("li", null,
                        React.createElement("p", null, "Node"))),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("p", null, "React")),
                    React.createElement("li", null,
                        React.createElement("p", null, "Angular")),
                    React.createElement("li", null,
                        React.createElement("p", null, "TypeScript")),
                    React.createElement("li", null,
                        React.createElement("p", null, "AWS"))),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("p", null, "Azue")),
                    React.createElement("li", null,
                        React.createElement("p", null, "Docker")),
                    React.createElement("li", null,
                        React.createElement("p", null, "Terraform")),
                    React.createElement("li", null,
                        React.createElement("p", null, "Jenkins")))))))); };
exports.default = (0, react_redux_1.connect)()(AboutMe);
//# sourceMappingURL=AboutMe.js.map